# Generated by Django 3.0 on 2020-01-06 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='collaborators',
            new_name='collaborator',
        ),
    ]
