# Generated by Django 3.0 on 2020-01-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_about_centre_committee_committee_member_home_patent_people_project_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='academic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('brief1', models.CharField(max_length=40)),
                ('brief2', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, upload_to='home/static/home/images/facilities')),
                ('function', models.CharField(max_length=1500)),
                ('remarks', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=300)),
                ('brief', models.CharField(max_length=1500)),
                ('link', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='home/static/home/images/news')),
            ],
        ),
        migrations.AddField(
            model_name='collaborator',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
