# Generated by Django 3.0 on 2020-02-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200124_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='director_message',
            field=models.CharField(max_length=5000),
        ),
    ]
