# Generated by Django 3.0 on 2020-02-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200213_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centre',
            old_name='name',
            new_name='centre_name',
        ),
        migrations.AddField(
            model_name='centre',
            name='content',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='centre',
            name='content_topic',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='centre',
            name='image',
            field=models.ImageField(blank=True, upload_to='home/static/home/images/centres'),
        ),
    ]
