# Generated by Django 3.0 on 2020-02-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200213_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='copi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pi',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
