# Generated by Django 3.0 on 2020-02-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200213_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
