# Generated by Django 3.0 on 2020-02-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200213_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='middle_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
