# Generated by Django 3.0 on 2020-02-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200213_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
