# Generated by Django 3.0 on 2020-03-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200315_0247'),
        ('home', '0007_auto_20200127_1929'),
    ]

    operations = [
    ]
