# Generated by Django 3.0 on 2020-03-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_merge_20200315_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='designation',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='people',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='publication',
            name='yop',
            field=models.CharField(max_length=10),
        ),
    ]
