# Generated by Django 3.0 on 2020-03-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200330_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='bio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
