# Generated by Django 3.0 on 2021-05-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20200330_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='image',
            field=models.ImageField(blank=True, upload_to='kavikishna_lab/static/home/images/people'),
        ),
    ]
