# Generated by Django 3.0 on 2021-05-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20210512_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='image',
            field=models.ImageField(blank=True, upload_to='kavikrishna_lab/static/home/images/people'),
        ),
    ]
